### ISSUE TITLE
Add own mods via volume?

### ISSUE THREAD

**Issue by adsads** [hexlo/terraria-tmodloader-server#2]
I'm looking to add RecursiveCraft to this. Can I just map the mod folder as a volume and add it that way?

https://github.com/Ishigh1/RecursiveCraft

Thanks

**Comment by hexlo** [comment]
This image downloads all the latest versions of the mods at build time, so I have to add new ones manually. I'll test this one and add it asap.

As for adding the ability to mount a volume for people to provide their own mods, I will look at it, but can't promise you anything.

Cheers

**Comment by RadioactiveHydra** [comment]
Whoops, I did not mean to ping this issue (I wanted to type in just number 2), but I am also working on something that addresses this.

**Comment by hexlo** [comment]
Updated for tModLoader 1.4.4. Uses latest stable release and updates every hour. You can also add mods by Steam Workshop ID or by mounting them in the tModLoader/steamapps/workshop/content directory.
