### ISSUE TITLE
You are on tModLoader v2022.9.47.46!2022.9.47, server is on tModLoader v0.11.8.9

### ISSUE THREAD

**Issue by timdonovanuk** [hexlo/terraria-tmodloader-server#6]
Hi,

I think this image is now using an outdated versions of tModLoader.

How can it be updated? Thanks.

Thanks,

**Comment by brendonmconnett** [comment]
+1

**Comment by hexlo** [comment]
Updated for tModLoader 1.4.4. Using latest release and updating every hour.
